### ISSUE TITLE
--max_seq_length=128 -> 150

### ISSUE THREAD

**Issue by dsindex** [kyzhouhzau/BERT-NER#1]
hi kyzhouhzau~ 

thank you for this project :)
there is a minor error which i'd like to report. 

```
def convert_single_example(ex_index, example, label_list, max_seq_length, tokenizer):
...
    input_ids = tokenizer.convert_tokens_to_ids(ntokens)
    input_mask = [1] * len(input_ids)
    while len(input_ids) < max_seq_length:
        input_ids.append(0)
        input_mask.append(0)
        segment_ids.append(0)
        label_ids.append(0)
    print('length check', len(input_ids), max_seq_length)
    assert len(input_ids) == max_seq_length  <-- error
    assert len(input_mask) == max_seq_length
    assert len(segment_ids) == max_seq_length
    assert len(label_ids) == max_seq_length
...
```

`tokenizer.convert_tokens_to_ids(ntokens)` would generate longer list than `max_seq_length` when we are using  `--max_seq_length=128`.

so, i ran with `--max_seq_length=150`. it was fine.

**Comment by kyzhouhzau** [comment]
Thanks for your suggestions. Indeed, <code>--max_seq_length=150</code> will have a better result.

**Comment by kyzhouhzau** [comment]
> hi kyzhouhzau~
> 
> thank you for this project :)
> there is a minor error which i'd like to report.
> 
> ```
> def convert_single_example(ex_index, example, label_list, max_seq_length, tokenizer):
> ...
>     input_ids = tokenizer.convert_tokens_to_ids(ntokens)
>     input_mask = [1] * len(input_ids)
>     while len(input_ids) < max_seq_length:
>         input_ids.append(0)
>         input_mask.append(0)
>         segment_ids.append(0)
>         label_ids.append(0)
>     print('length check', len(input_ids), max_seq_length)
>     assert len(input_ids) == max_seq_length  <-- error
>     assert len(input_mask) == max_seq_length
>     assert len(segment_ids) == max_seq_length
>     assert len(label_ids) == max_seq_length
> ...
> ```
> `tokenizer.convert_tokens_to_ids(ntokens)` would generate longer list than `max_seq_length` when we are using `--max_seq_length=128`.
> 
> so, i ran with `--max_seq_length=150`. it was fine.

Thanks for your suggestions. Indeed,<code> --max_seq_length=128</code> will have a better result.

**Comment by kyzhouhzau** [comment]
@dsindex 
Thanks for your suggestions. Indeed, <code>--max_seq_length=128</code> will have a better result.
