### ISSUE TITLE
Which tf version and python version should be used?

### ISSUE THREAD

**Issue by wead-hsu** [kyzhouhzau/BERT-NER#17]
I can not run the scripts. The program fails:
![image](https://user-images.githubusercontent.com/7287692/49862339-ea759c00-fe38-11e8-87dc-2d83ff645a66.png)
Do you have any idea why this happens?

**Comment by wead-hsu** [comment]
It turns out to be a personal issue.

**Comment by SmartMapple** [comment]
hello, how your sloved it? i met the same question.

**Comment by wead-hsu** [comment]
> hello, how your sloved it? i met the same question.

Sorry, I do not remember how I solved
